### ISSUE TITLE
Lightwalletd API Documentation

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#131]
As a wallet developer, I would like comprehensive lightwalletd documentation that makes it easy for me to understand how to interact with lightwalletd to receive blockchain information and broadcast transactions.

Criteria: godoc generated HTML output that

1) All lightwalletd API endpoints are documented to include:
    1a) the request path
    1b) required parameters
    1c) expected return type
2) The documentation is included in the lightwalletd README

**Comment by lindanlee** [comment]
Repointed for the new sprint, since some work was done past sprint.

**Comment by lindanlee** [comment]
This was not finished for sprint 2020:09, comment if partial work was done for re-pointing.

**Comment by lindanlee** [comment]
Larry would like to add more text to this, especially about the API parameters and return values.

**Comment by lindanlee** [comment]
Not completed for sprint 2020:09, recommitted for next sprint.

**Comment by lindanlee** [comment]
This may be done.

**Comment by lindanlee** [comment]
Larry will rebase, merge, and close asap! This has been around too long. :)
