### ISSUE TITLE
Unit Tests Using Mocking Layer

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#163]
As a lightwalletd developer, I would like a comprehensive testing suite to reliably test interactions with the zcashd RPC without having to run a zcashd node to keep the testing suite self contained.

Acceptance Criteria:
- [x] Lightwalletd library test coverage to 80% (coverage is 53.2% at start of ticket)

**Comment by LarryRuane** [comment]
Merged https://github.com/zcash/lightwalletd/pull/164
