### ISSUE TITLE
Don't log RPC calls/statistics

### ISSUE THREAD

**Issue by defuse** [zcash/lightwalletd#180]
Presently, `lightwalletd` logs whenever a gRPC gets called: https://github.com/zcash/lightwalletd/blob/59170d491132d0799643ba765753c89f8fd899b3/cmd/server/main.go#L51. As explained [here](https://github.com/zcash/lightwalletd/pull/172#pullrequestreview-350342997), these logs risk compromising the privacy of lightwalletd users, and must not be enabled in production environments.

**Comment by LarryRuane** [comment]
Closing; this was fixed by #333.
