### ISSUE TITLE
use local disk storage to improve block cache

### ISSUE THREAD

**Issue by LarryRuane** [zcash/lightwalletd#182]
In this thread: https://zcash.slack.com/archives/GD4G0S0AF/p1580408638108900 Kevin (@gmale) discusses the possibility of adding SQL back to lightwalletd, or using Redis to improve performance. I have given this a lot of thought, and I think I have a better idea. I want to store all compact blocks since Sapling activation in a local file, in such a way that lightwalletd restart time will be practically zero (after of course downloading the blocks from `zcashd` the first time), and accessing a compact block for a wallet request (i.e. `GetBlock` and `GetBlockRange` gRPC calls) will be at least an order of magnitude faster than today when the block isn't in the (limited size) cache. I don't think we need an actual database (SQLite or Redis). A database is great when objects are mutable; blocks are immutable. So we can store them as just a linear sequence of variable-length records on disk. This is exactly what `zcashd` (and bitcoin core) do in their `~/.zcashd/blocks/blk000???.dat` files. This file will only be about 50 MB (I did a quick experiment to determine this).

I have figured out too how to handle reorgs -- that's the one case where the blocks we've stored on disk need to be changed, but that's just changing the tip of the file, which is easy to overwrite.

The nice things about using a file are (1) the restart time is almost zero (no need to re-download the blocks from `zcashd`, and (2) the lightwalletd memory footprint is very small, even though we're storing all blocks since Sapling. Reading blocks from the file will be slightly slower than having them in a memory cache, but I think the difference will be minor and acceptable. If not, and if a larger memory footprint isn't much of a problem, we can cache them (or at least some of them) in memory _and_ still store them in a file.

**Comment by LarryRuane** [comment]
I'll explain a little more about the design I have in mind. When lightwalletd starts the first time, it will request all the blocks since Sapling from `zcashd`, converting each to a `CompactBlock`. It does this today and stores the compact blocks in its in-memory cache, and by default does not go all the way back to the beginning of Sapling. 

The new design will create two files, `mainnet-index` and `mainnet-blocks` (or `testnet-index` and `testnet-blocks`), and append the compact blocks to `mainnet-blocks` and append the length of the block to `mainnet-index`. In my testing, this takes about 40 minutes on mainnet. In the current design, which uses an in-memory cache, this occurs every time lightwalletd starts up (although the time reduces to about 10 minutes by using the default `-cache-size`, 80k, but then block requests by wallets that go back farther than that are much slower).

I estimate that the `mainnet-blocks` file, which is a simple concatenation of all compact blocks since Sapling, will be (at the current height, around 700k blocks) about 50 MB. The `mainnet-index` file is a simple array that contains the 4-byte length for each block, starting with Sapling's first block, so will be about 1 MB in length.

In the new design, creating and populating these two files happens only once (let's call this initial sync or initial block download), only if these files don't exist. If they do exist, then when lightwalletd starts up it will open and read the `mainnet-index` file in a single operation. Then the startup code will loop through this array and create a slice (array) of each block's starting offset in the `mainnet-blocks` file. For example, if `mainnet-index` begins with:
```
78
100
100
```
then the `BlockStarts` array will begin with:
```
0
78
178
278
```
The first block's offset (in `mainnet-blocks`) is 0, the second block begins at byte offset 78, and so on. File offsets are 8 bytes, so this array will (initially, at current block height) be only 2 MB, which is a trivially-small amount of memory.

That's all there is to startup. These steps can be performed in a fraction of a second.

Now, when a request for a block arrives (by height, as today), then we index into the `BlockStart` array using the expression `blockNumber-SaplingHeight`, seek to that offset in `mainnet-blocks`, read the `CompactBlock` (which will already be serialized, the same as with the cache today) into temporary memory, and reply to the request.

When the `BlockIngestor` thread receives a new block from `zcashd` (it will poll for them every few seconds, as it does today), it will calculate the compact block, append it to `mainnet-blocks`, fsync the file (to make sure it's been written to disk), append the compact block's length to `mainnet-index`, fsync that file, and append the new entry's file offset to the memory array `BlockStarts`. 

A `CompactBlock` contains the block's hash and prev-hash, so a reorg can be detected. If a reorg is detected, we'll simply back up a few blocks by truncating those blocks from the end of both files (a very cheap operation), remove the last few entries from the in-memory `BlockStarts` array, and then continue the normal process of polling for blocks. This process of backing up can occur multiple times with no special processing needed. (This is exactly analogous to the way the cache reacts to reorgs in the current design.) 

So only the tips of the files ever need to be rewritten.

What happens if a reorg occurs while this lightwalletd is not running? Nothing special has to happen; the first time it polls for and receives a block from `zcashd` on the correct chain (moments after it starts0, it will back up a few blocks (multiple times if necessary) and get back on the consensus chain. 

Two small modifications: First, we should also put a 4-byte "magic number" before each compact block in `mainnet-blocks` so that we can detect file corruption. (This is exactly what `zcashd` and `bitcoind` do with their `blocks/blk000nnn.dat` files.) If the file is ever found to be corrupt, we can simply delete it and start from scratch (downloading blocks again from `zcashd`); this should be a very rare event. 

Second, we should begin each file with a version number (or string) in case the format ever changes. If we do read an unknown version, we can simply delete the files and recreate them (no need for any kind of fancy conversion or recovery).

**Comment by gmale** [comment]
This sounds very efficient and it sounds like something that would work.

At the same time, it seems to be effectively defining a proprietary data format coupled with a custom protocol for accessing and parsing that format.

In general, I agree with this statement:

> Reading blocks from the file will be slightly slower than having them in a memory cache, but I think the difference will be minor and acceptable.

And it seems like similar logic can be applied to working with an established data solution vs. a proprietary approach: a zcash-specific solution would be faster and smaller than Redis or a relational database but I think the difference will be minor and acceptable.

Maybe a middle-ground would be to research the popular RDBMS & [IMDB](https://devopedia.org/in-memory-database) solutions and see which one serves us best. Some potential candidates:

- Redis
- [Badger](https://blog.dgraph.io/post/badger-over-rocksdb-in-dgraph/)
- Apache Ignite
- RocksDB
- Memcached
- H2
- [Aerospike](https://www.aerospike.com/products/features/hybrid-memory-architecture/)
