### ISSUE TITLE
Test lightwalletd godoc HTML outputs on rtd

### ISSUE THREAD

**Issue by lindanlee** [zcash/lightwalletd#185]
Work with marshall to get a test page up for the wallet team to see. 

Acceptance criteria:
- [ ] generate HTML page hosted by read the docs
- [ ] show team resulting page in a parking lot

**Comment by lindanlee** [comment]
We're giving Marshall until the end of the sprint to investigate the solution that we chose (#1). If we do not figure out how to get this working, then we will fall back to the alternative (#2). 

--

**#1: Host the scripts to generate the docs on the repo, CI runs the script whenever there is a new github tag.** 

+: automated documentation, fresh per release 
+: abstracts away how documentation works from CI 
-: more difficult to implement in CI; _our mac infra is not mature and this may not be possible_ 

**#2: Host the docs on the repo (bloaty), and CI pulls .html files whenever there is a new github tag.** 

+: automated documentation, fresh per release 
+: abstracts away how documentation works from CI 
-: bloated repo (although our docs are small at the moment) 
-: breaking conventions (people don't normally host docs with the source code) 

Notes for #2: 
* All docs must be at repo/docs/rtd/index.html --having it in a consistent place across all repos means that he doesn’t have to sort of hard-code different paths for each repo. Name the file index.html, and do not change it--changing it would break the CI build. 
* Automate generating this documentation per build by adding a line to the makefile.

**Comment by LarryRuane** [comment]
We've decided that lightwalletd will take approach 2 (the docs are already in the correct place in the `master` branch, #188).

**Comment by lindanlee** [comment]
Larry and I decided on a way to automate generating docs, but not to have it part of the makefile to build every time, because documentation doesn't change that much. It's when we add/subtract wallet rpc functionality, or dramatically change (i.e. change the inputs) to existing wallet rpc functionality. 

In short, the documentation will only change when the .protofiles change. 

It's possible to fire off the makefile action that builds the docs whenever the .proto files change
