### ISSUE TITLE
add COPYING file and copyright lines to source files

### ISSUE THREAD

**Issue by LarryRuane** [zcash/lightwalletd#193]
We should add a `COPYING` file (probably from the zcash repo is close or perfect) to the top-level directory, and add copyright lines to all source files, for example (this is from a typical zcashd file):
```
// Copyright (c) 2020 The Zcash developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://www.opensource.org/licenses/mit-license.php .
```
(Does this also need to be done for the other wallet repos?)

**Comment by braddmiller** [comment]
@LarryRuane MIT License looks good and it's what we put on everything. Adding a 1 point estimate since it's just a docs change. You can reference librustzcash if you'd like for wording on how we license libraries.
