### ISSUE TITLE
Research Spike: Deployment Guides

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#198]
The current state of lightwalletd deployment is fairly polished but somewhat unclear as multiple parties and teams have worked on it. The intent of this research spike is to consolidate all of that information and should result in a list of PRs from any remaining deployment work that should be merged to lightwalletd master and a ticket to update the README with the current recommended method of deploying lightwalletd.

Timebox: 4 hours

Outcomes:
- [x] List of PRs or commits that should be merged back to lightwalletd master
- [ ] A ticket outlining the README changes that need to be merged.

**Comment by LarryRuane** [comment]
PRs to be merged:
- https://github.com/zcash/lightwalletd/pull/172 (Add http endpoint and prometheus metrics framework)
- https://github.com/zcash/lightwalletd/pull/175 (Use cobra and viper for configuration)

Also, CI for docker image builds (no ticket yet, Ben is writing one).

I don't think we should update `README.md` using a separate ticket; those PRs should include appropriate updates to that file. I made comments in those PRs asking that they include `README.md` updates.

**Comment by LarryRuane** [comment]
@benzcash just created this, a third and I think final PR for this research spike:

#215 (Add docker image build and upload to CI)

**Comment by lindanlee** [comment]
Linda is coordinating with Ben to get this done.
