### ISSUE TITLE
Implement data sets for triggering reorg tests

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#199]
Create data sets to trigger the following reorgs without transactions associated to the wallet in them:

Requirements:
- [ ] Data set exists to trigger a short (<10 blocks) reorg
- [x] Data set exists to trigger a long (>10 blocks) reorg

**Comment by defuse** [comment]
https://github.com/zcash/lightwalletd/pull/190 will enable lightwalletd to run without connecting to a zcashd, instead sending RPCs to an internal mock zcashd which can be controlled via two new gRPCs:

1. EvilSetState: lets you provide a list of blocks (hex-encoded), the height that the first block in the list should be, the sapling activation height, branch ID, and chain name.
2. EvilGetIncoming: lets you retrieve the transactions that wallets have delivered to lightwalletd for delivery to the zcash network.

I have a big wishlist of tests [in this google doc](https://docs.google.com/document/d/1_pC-uD7FdG8sMqVuuAXOoi9jFJlT9o3_Bg-WvJMfpwo/edit?usp=sharing) but the basic transaction-disappearing / transaction-appearing-in-a-different-block reorg tests are the most important.

These two new gRPCs should be sufficient to implement the reorg tests, the only caveat is that it's up to the test code to produce the blocks that the mock zcashd will serve (normally the miners do it). This means, for example, if you want to write a test where two wallets are sending payments to each other, the test code will have to produce the blocks containing the payments and feed them up to darksidewalletd. *Neither lightwalletd nor the wallets actually perform many of the block/transaction validity tests, so thankfully the test code won't actually need to produce valid blocks.*

**Comment by defuse** [comment]
The steps for writing the basic reorg tests are:

1. Create the "before" state blocks.
2. Create the "after" state blocks which are just like the "before" state except a transaction disappeared or moved to a different block.
3. Write a test that:
    i. Loads darksidewalletd in the "before" state.
    ii. Syncs the wallet.
    iii. Reloads darksidewalletd in the "after" state
    iv. Observes how the wallet handled the reorg.

Most of the work will be in (3) -- developing the test harnesses for iOS and Android but (1) and (2) might run into some snags getting blocks/transactions to pass whatever extra validation the wallets do on top of what lightwalletd already does.

**Comment by lindanlee** [comment]
Points to be assigned after Taylor's meeting and explanation.

**Comment by lindanlee** [comment]
Waiting for Taylor to review and pull things in, Larry has made some changes based on Kevin and Pacu's feedback.

**Comment by LarryRuane** [comment]
This ticket is done, isn't it? The data sets have been created here: https://github.com/zcash-hackworks/darksidewalletd-test-data

Will more data sets be needed? If so, I don't think I should be assigned to this ticket; it depends on @pacu and @gmale.

**Comment by braddmiller** [comment]
We still need to create a reorg with a wallet-involved transaction. Not sure who is best suited to created that, can discuss in standup
