### ISSUE TITLE
darksidewalletd: set coinbase height correctly in fake blockchain tool

### ISSUE THREAD

**Issue by defuse** [zcash/lightwalletd#203]

**Comment by LarryRuane** [comment]
Can you please explain to me what coinbase height is and the advantage of setting it correctly?

**Comment by defuse** [comment]
TODO: After #186 merges there'll be a  `TODO COINBASE-HEIGHT: restore this check after coinbase height is fixed` comment in the code to address once this is done.

@LarryRuane Sorry I missed your comment, I think you already understand but the issue is just that the fake blocks generated by the fake-block-generating tool don't have the correct block heights encoded in their coinbase transaction because I lazily copypasted some random coinbase transaction to use in all of the blocks.
