### ISSUE TITLE
Automate a basic reorg test for lightwalletd using darksidewalletd

### ISSUE THREAD

**Issue by defuse** [zcash/lightwalletd#205]
I caught #204 using darksidewalletd manually, but it's the kind of thing that should be automated and run in CI. Close this ticket by automating the steps in #204.

**Comment by LarryRuane** [comment]
I think this can be closed, it was fixed as part of: https://github.com/zcash/lightwalletd/pull/363/files#diff-3c3c4b8cc27e8d0bfb5304aed0335a263a06d7ccbfb224fdcd7ac8ff851f34af
