### ISSUE TITLE
Tech debt tickets (lightwalletd)

### ISSUE THREAD

**Issue by lindanlee** [zcash/lightwalletd#211]
Comment below on any tech debt worked on this sprint. Linda will update the ticket points with the amount of work done for the sprint after-the-fact.

**Comment by LarryRuane** [comment]
- [ ] if `zcashd` is restarted while `lightwalletd` is running, it does the right thing -- unless you switch `zcashd`'s chain (mainnet, testnet). In this case, `lightwalletd` should detect that this happened, print and log an error, and quit. (It's difficult to make it dynamically switch chains.) This will be more beneficial for testing than production, but still worth doing, and easy.
