### ISSUE TITLE
Create darksidewalletd initial test data sets

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#212]
Generate darksidewalletd test data sets

Requirements:
- [ ] Generate a test data set of existing chain data without a reorg
- [ ] Generate a test data set of a reorg of <10 blocks
- [ ] Generate a test data set of a reorg of >10 blocks
- [ ] Block range is 663150 - 663250

**Comment by lindanlee** [comment]
Needs review and merge. @defuse

**Comment by braddmiller** [comment]
This, as written, is complete. Making a follow up ticket for more comprehensives including transactions being reorged related to wallets.
