### ISSUE TITLE
Auto-update docs when .proto files change.

### ISSUE THREAD

**Issue by lindanlee** [zcash/lightwalletd#213]
The documentation will only change when the .protofiles change.  It's possible to fire off the makefile action that builds the docs whenever the .proto files change, to ensure doc freshness. 

Context: This is a way to automate generating docs, but not to have it part of the makefile to build every time, because documentation doesn't change that much. It's when we add/subtract wallet rpc functionality, or dramatically change (i.e. change the inputs) to existing wallet rpc functionality. 

Part of the "keep docs automatically updated" epic. We've decided to go ahead and keep index.html files in docs/rtd on github for marshall.

**Comment by LarryRuane** [comment]
There's an additional similar thing to do when the `.proto` files change: regenerate the `*.pb.go` files, which are in source control (because we don't want to require everyone to have `protoc` installed). This ticket can serve for both. I have a good start on this already.

**Comment by lindanlee** [comment]
Nice! Sounds good to me.
