### ISSUE TITLE
loggerFromContext(): Anonymize the addresses, cryptopan?

### ISSUE THREAD

**Issue by LarryRuane** [zcash/lightwalletd#217]

**Comment by LarryRuane** [comment]
No one knows what this means (was just a TODO comment in the code), will re-open if it becomes clear.

**Comment by defuse** [comment]
It's referring to https://en.wikipedia.org/wiki/Crypto-PAn, which is a way to log identifiers like IP addresses (and in this case zcash addresses) more privately. I don't think it's worth the effort at this point.
