### ISSUE TITLE
Darksidewalletd getting started instructions for Linda

### ISSUE THREAD

**Issue by lindanlee** [zcash/lightwalletd#226]
Write instructions for Linda so that she can start testing/reviewing code for darksidewalletd. We can use the artifacts to turn them into documentation later on. 

The information should contain: 
- [x] how to run darksidewalletd 
- [x] a list of basic tasks to try with commands (cause a reorg, make your own block, etc.) 
- [x] what parts of the darksidewalletd code to review

**Comment by braddmiller** [comment]
@lindanlee this is done correct?

**Comment by defuse** [comment]
The PR is up here: https://github.com/zcash/lightwalletd/pull/247

(It will need to be updated after Larry's most recent changes merge)

**Comment by defuse** [comment]
This has been merged
