### ISSUE TITLE
Implement a general purpose block service API

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#235]
As a wallet developer, I would like to be able to write tests with arbitrary mock block data and provide it to a consistent API in the block server.

Requirements:
- [ ] A `serveRawBlocks` api call that accepts raw block data as a parameter to change the selected blocks to be served
- [ ] A `serveUrlBlocks` api call that accepts a url to serve blocks from a file stored at a public endpoint

Reference: 
https://docs.google.com/presentation/d/1qUCqAjz1uVQmOGDQFUNc8-4raGNyU8hekTPjm6WzGec/edit?usp=sharing

**Comment by LarryRuane** [comment]
This can be closed, right? It's out of date and superseded by these more specific 7 tickets: #253, #254, #255, #256, #257, #259, #261.
