### ISSUE TITLE
Implement gettransaction in darksidewalletd

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#244]
Implement the gettransaction call in darksidewalletd referencing this document for design and reasoning.

https://docs.google.com/presentation/d/1qUCqAjz1uVQmOGDQFUNc8-4raGNyU8hekTPjm6WzGec/edit?usp=sharing

**Comment by lindanlee** [comment]
Grab hex encoded blocks, decode the transactions, figure out the format wallet needs, make that searchable, and when a wallet request a transaction, search it and give the correct transaction back to the wallet.
