### ISSUE TITLE
Create API: Reset

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#253]
Create an API `Reset` to reset darksidewalletd.  This is intended to be run before each independent test, so that no state "leaks" from one test to the next. See [darkside.proto](https://github.com/zcash/lightwalletd/blob/da9420fc1ddef84b58190c8a8418c832bda04371/walletrpc/darkside.proto) for details.

Requirements:
- [x] All previous darkside state is cleared (staging area, incoming transactions list)
- [x] Takes dWD and LWD state back to initial state
- [x] Must be synchronous -- when this gRPC returns, the test can immediately proceed
- [x] The gRPC session must not disconnect (i.e. it's not acceptable to restart the process)
- [x] This entire operation must happen in less than 500ms
- [x] Does not trigger reorg behavior in LWD

**Comment by LarryRuane** [comment]
This is done, ready to review and attempted use by Kevin and Pacu. In branch for PR https://github.com/zcash/lightwalletd/pull/250, not yet master.
