### ISSUE TITLE
Create API: ClearIncomingTransactions

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#255]
While in darkside mode, the `SendTransaction` production gRPC handler stores the received transaction in the "incoming transaction list" for later retrieval by the `GetIncomingTransactions` darkside (test) gRPC. The `GetIncomingTransactions` gRPC returns the entire list but doesn't clear it. Those gRPCs are already implemented, but remaining to be done is implement `ClearIncomingTransaction` to delete the entries in the list (without having to do a `Reset`, which is a much bigger hammer). This is a small task.

**Comment by pacu** [comment]
I think this si no longer needed or it requires some serious rephrasing

**Comment by LarryRuane** [comment]
This is done, ready to review and attempted use by Kevin and Pacu. In branch for PR https://github.com/zcash/lightwalletd/pull/250, not yet master.
