### ISSUE TITLE
Create API: StageBlocksCreate

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#257]
Create a the `StageBlocksCreate` API to add blocks to the staging area.
 See [darkside.proto](https://github.com/zcash/lightwalletd/blob/da9420fc1ddef84b58190c8a8418c832bda04371/walletrpc/darkside.proto) for details.

Requirements:
- [x] Construct "valid" synthetic empty blocks for darkwalletd, as the `genblocks.go` tool does
- [x] Accepts a count, the number of blocks to generate
- [x] Accepts an integer for the starting height (the height of the first block in the series)
- [x] Accepts a "nonce" which can be used to make this block's hash unique (even among blocks of the same height)
- [x] Adds these blocks to the staging area

The return value is always success.

**Comment by LarryRuane** [comment]
This is done, ready to review and attempted use by Kevin and Pacu. In branch for PR https://github.com/zcash/lightwalletd/pull/250, not yet master.
