### ISSUE TITLE
Create API: ApplyStaged

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#259]
Create an API to "inject" all staged transactions (if any) into the staged blocks they're associated with, then "merge" all staged blocks (if any) into the active blockchain (what is presented by the mock zcashd). Merging means each staged block replaces the active blocks at the same height, if one exists.

This API is the only means by which chain reorgs can occur, but it may also be used to simply reveal additional blocks (by advancing the height) without a reorg.

The active chain may (and usually does) contain blocks at heights _higher_ than the "latest" height (as returned by `GetLatestBlock`); they are simply not revealed; as the height is increased (using this gRPC), additional blocks are revealed. Blocks in the active chain that are not revealed should not be confused with blocks in the staging area. 

Move the current "chain tip" to the given value. See [darkside.proto](https://github.com/zcash/lightwalletd/blob/da9420fc1ddef84b58190c8a8418c832bda04371/walletrpc/darkside.proto) for details.

Format: `ApplyStaged(Int Height)`

Requirements:
- [x] All actions of this gRPC must be atomic
- [x] Blocks are applied in the order they are staged
- [x] sets the current chain tip to specified height, which can be higher or lower than before
- [x] If attempting to set the height greater than maximum block height of data set, crash
- [x] If no block exists at a staged transaction's height, this is an error, crash
- [x] The staging areas (both transactions and blocks) are cleared
- [x] It is not an error if either or both staging areas are empty; the effect is simply to adjust the height
- [x] Transactions in the active chain that have been revealed (in blocks with heights less than or equal to the current tip) are fetchable by the production `GetTransaction` gRPC.

**Comment by LarryRuane** [comment]
This is done, ready to review and attempted use by Kevin and Pacu. In branch for PR https://github.com/zcash/lightwalletd/pull/250, not yet master. The only slight differences from the checklist above are that instead of crashing, we return an error, as this makes it easier for Pacu and Kevin to understand the failure.
