### ISSUE TITLE
darkwalletd dataset: Spendable transactions in block range

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#266]
Range of blocks with spendable transactions at given heights

Requirements:
- [x] A range of blocks with 3 incoming transactions in 3 different blocks

Notes:
@pacu Please add txid and height for the desired transactions in a comment

**Comment by LarryRuane** [comment]
Done, actually, it was convenient to include 4 transactions instead of 3: https://github.com/zcash-hackworks/darksidewalletd-test-data/tree/master/tx-incoming

I took the txids and heights from https://github.com/zcash/zcash-android-wallet/issues/114.
