### ISSUE TITLE
Add GetBalance RPC

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#294]
The wallets would like to be able to receive their balance for a given t-address by requesting it from LWD.

Requirements:
- [ ] Return balance given a single t-address

**Comment by LarryRuane** [comment]
Correction, the rpc that's needed is `getaddressbalance`. (The `getbalance` rpc reports only the balance for addresses that are owned by this wallet.) I verified that `getaddressbalance` is available with `txindex` and `lightwalletd` enabled.
