### ISSUE TITLE
Research Spike: Permanent checkpoint solution

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#296]
Reduce time to create checkpoints to less than 15 minutes

Time Box: 4 hours

**Comment by lindanlee** [comment]
Kevin, Pacu, and Larry should pair for an hour, then go with an intermediate solution. Then run it by Taylor for review. 

Currently, checkpoints take 45min+.

**Comment by lindanlee** [comment]
Larry and Kevin have an initial plan and it requires some more iteration. However, we can consider this research spike done-ish, since we know the general direction we want to go.

**Comment by lindanlee** [comment]
Need to iron out the details, but will consider this research spike done. Will make follow up pointed tickets for work.
