### ISSUE TITLE
Research Spike: Systematically look for various DoS vulnerabilities

### ISSUE THREAD

**Issue by LarryRuane** [zcash/lightwalletd#314]
Generalization and continuation of #313. Needs to include attacks that cause memory exhaustion (very large inputs). This also includes guards against bad input from the `zcashd` that this lightwalletd is connected to.

Timebox:
Initial Review: 16 hours
Issue Confirmation: 16 hours

Output:
Tickets with proposed fixes for any issues uncovered

**Comment by braddmiller** [comment]
Done
