### ISSUE TITLE
Add zcashd version string to GetLightdInfo result

### ISSUE THREAD

**Issue by LarryRuane** [zcash/lightwalletd#319]
Requested by @gmale 
Example output:
```
{
  "version": "v0.4.3",
  "vendor": "ECC LightWalletD",
  "taddrSupport": true,
  "chainName": "main",
  "saplingActivationHeight": 419200,
  "consensusBranchId": "e9ff75a6",
  "blockHeight": 1047744,
  "lwdGitCommit": "20105167b8acf77e649ae9cac94431f101c50261",
  "zcashdGitCommit": "blahblahblahblahblahblahblah",
  "buildDate": "2020-10-11",
  "buildUser": "root"
}
```

**Comment by gmale** [comment]
we could possibly add zcashdVersion, as well (to display 4.1.1)

**Comment by LarryRuane** [comment]
Here's what we currently get from the cli rpc (note this happens to be testnet):
```
$ src/zcash-cli getinfo
{
  "version": 4010150,
  "protocolversion": 170013,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 842202,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 24.08075727890571,
  "testnet": true,
  "keypoololdest": 1589318109,
  "keypoolsize": 109,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": "",
  "errorstimestamp": 1605816272
}
```
Let me know which of these items you'd like to see. One interesting one is `blocks` -- I ran the above while syncing with the network (so it's far behind tip). I'd think that's useful to you.

The following does report the abbreviated commit hash (partial output):
```
$ src/zcashd -version
Zcash Daemon version v4.1.1-54cfb9c49-dirty
(...}
```
Since lightwalletd doesn't have the ability to do this, let me know if that's important, we could do a small zcashd PR to add that string to its `getinfo` result (and then have `GetLightdInfo` include this in its output). My guess is that's not useful enough to do, but let me know if you think otherwise.

**Comment by gmale** [comment]
Definitely:
```
  "version": 4010150,
  "protocolversion": 170013,
```
The "Zcash Daemon Version" would probably depend on how complex it is to add.

**Comment by hendis85** [comment]
> Requested by @gmale
> Example output:
> 
> ```
> {
>   "version": "v0.4.3",
>   "vendor": "ECC LightWalletD",
>   "taddrSupport": true,
>   "chainName": "main",
>   "saplingActivationHeight": 419200,
>   "consensusBranchId": "e9ff75a6",
>   "blockHeight": 1047744,
>   "lwdGitCommit": "20105167b8acf77e649ae9cac94431f101c50261",
>   "zcashdGitCommit": "blahblahblahblahblahblahblah",
>   "buildDate": "2020-10-11",
>   "buildUser": "root"
> }
> ```
@hendisutrisno

  "version": "v0.4.3",
  "vendor": "ECC LightWalletD",
  "taddrSupport": true,
  "chainName": "main",
  "saplingActivationHeight": 419200,
  "consensusBranchId": "e9ff75a6",
  "blockHeight": 1047744,
  "lwdGitCommit": "20105167b8acf77e649ae9cac94431f101c50261",
  "zcashdGitCommit": "blahblahblahblahblahblahblah",
  "buildDate": "2020-10-11",
  "buildUser": "root"
}
