### ISSUE TITLE
How to call rpc from outside

### ISSUE THREAD

**Issue by hoangphuongcs** [zcash/lightwalletd#325]
I have a node on the Linux server.
And I can call RPC from the server.
But I can't call from my computer to the node by IP.
It's still a required password but it does not work and throw the message: **Failed to connect to 35.221.29.10 port 8232: Connection refused**

And I checked the port and see:
ubuntu@instance-1-zcash-testnet:~$ netstat -tulpn | grep 18232
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 **127.0.0.1**:18232         0.0.0.0:*               LISTEN      1172/zcashd     
tcp6       0      0 ::1:18232               :::*                    LISTEN      1172/zcashd    

this is my config:

rpcuser=admin
rpcpassword=xxx
testnet=1
server=1
rpcbind=0.0.0.0
rpcport=18232
experimentalfeatures=1
txindex=1
insightexplorer=1
rpcconnect=0.0.0.0
bind=0.0.0.0

Can you help me to config? thanks!

**Comment by gmale** [comment]
Can you provide the options you used to start lightwalletd and perhaps @LarryRuane can help you tweak them to work on your local machine.

There is also detailed documentation for how to setup everything, which should also be easier if you use docker.

**Comment by hoangphuongcs** [comment]
thanks, I got a solusion!
