### ISSUE TITLE
Resolve Lightwalletd research spike DoS Findings

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#329]
Referencing internal research doc, resolve the following issues (check when code has been implemented but not committed)
- [x] Resolve Issue I
- [x] Resolve Issue J
- [x] Resolve Issue K

**Comment by LarryRuane** [comment]
These will have separate PRs when implemented:

- [ ] A: zcashd rpcs should have timeouts
- [ ] B, C, D: gRPC handlers should check error returns from `json.Marshal()`
- [ ] E: `cache.Add()` should check bytes written to disk return value
- [ ] G: `GetTransaction()` should check length of txid argument (can't check format, it's binary)
- [ ] H: `cache.Add()` restore coinbase block height verification - done #331
