### ISSUE TITLE
Research Spike: NU5 changes to LWD and compact blocks

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#339]
This research spike is to understand changes required by NU5 to lightwalletd and the compact block format to help us estimate the time required to upgrade.

Time box: 2 hours (adjusted and carried over from last sprint)

**Comment by LarryRuane** [comment]
The task will be to compare the [ZIP-225 Orchard (NU5) spec](https://github.com/zcash/zips/blob/master/zip-0225.rst) to the existing Sapling-specific code in lightwalletd.

**Comment by LarryRuane** [comment]
Results:

In `walletrpc/compact_formats.proto`, the following changes will be needed to support transaction version 5, see [ZIP-0225](https://github.com/zcash/zips/blob/master/zip-0225.rst). (Note that this diff includes a simple rename to indicate Sapling-specific fields):
```diff
--- a/walletrpc/compact_formats.proto
+++ b/walletrpc/compact_formats.proto
@@ -37,20 +37,33 @@ message CompactTx {
     //    valueBalance + (sum(vPubNew) - sum(vPubOld) - sum(tOut))
     uint32 fee = 3;
 
-    repeated CompactSpend spends = 4;   // inputs
-    repeated CompactOutput outputs = 5; // outputs
+    repeated CompactSaplingSpend spends = 4;   // inputs
+    repeated CompactSaplingOutput outputs = 5; // outputs
+    CompactOrchard = 6;
 }
 
-// CompactSpend is a Sapling Spend Description as described in 7.3 of the Zcash
+// CompactSaplingSpend is a Sapling Spend Description as described in 7.3 of the Zcash
 // protocol specification.
-message CompactSpend {
+message CompactSaplingSpend {
     bytes nf = 1;   // nullifier (see the Zcash protocol specification)
 }
 
 // output is a Sapling Output Description as described in section 7.4 of the
 // Zcash protocol spec. Total size is 948.
-message CompactOutput {
+message CompactSaplingOutput {
     bytes cmu = 1;          // note commitment u-coordinate
     bytes epk = 2;          // ephemeral public key
     bytes ciphertext = 3;   // ciphertext and zkproof
 }
+
+message CompactOrchard {
+    repeated CompactOrchardActions = 1;
+}
+
+message CompactOrchardActions {
+    bytes nullifier = 1;
+    bytes cmx = 2;          // The x-coordinate of the output note commitment
+    bytes epk = 3;          // ephemeral public key
+    bytes ciphertext = 4;   // ciphertext and zkproof
+}
```
It's possible that it may be discovered that some per-transaction, but not per-action, additional fields will be needed within `CompactOrchard`, but currently this isn't expected.

Code will be added to `parser/transaction.go` to parse these fields.
