### ISSUE TITLE
Make darksidewalletd compatible with getAddressUtxo call

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#344]
Right now darksidewalletd is not compatible with the new getAddressUtxo call for lightwalletd.

Desired outcome: In darksidewalletd mode the getAddressUtxo call will return the correct results based on the blocks that have been created in the darkwalletd instance

**Comment by LarryRuane** [comment]
Merged. But the plan to "return the correct results based on the blocks that have been created in the darkwalletd instance" did not pan out; it was necessary to add a new darksidewallet gRPC to populate the list of Utxos which are then returned by the production gRPC `GetAddressUtxos`. Kevin and Pacu said this is okay.
