### ISSUE TITLE
Restore my wallet with the seeds and a balance does not appear

### ISSUE THREAD

**Issue by Cachari** [zcash/lightwalletd#353]
I created two wallets, both of my property, I sent one to the other in t> z format .... the money came from my wallet A to B, I had my money in B, but I decided to reset the application with the seeds and to my surprise my balance was not restored, my balance appears at zero 0

In the file that appears in APPDATA called "zecwallet-light-wallet.debug.log" there appears the transaction registered and with a certain block

I recovered my wallet with version 1.6 and 1.3 and my balance does not appear, it is still at zero and I transferred 2.7 ZEC

I'm anguished, I feel that the money was lost and what a bad day that the first time I try zecwallet, this happens to me, I don't know what to do

This is the TIXD of the transaction you make https://blockchair.com/zcash/transaction/80fd2b6b827ddcd271d04e7c06cd1f48cfd6a3902412cd575e3164730525875a

I appreciate your help please, it is not fair that my money is lost.  Thank you!

**Comment by Cachari** [comment]
**PROBLEM SOLVED**

- Enter my seeds
- I clicked on "New Shielded Address" and "New Transparent Address" until the address to which I transferred appeared
- I clicked on "rescue" and when I finished the last block my balance appeared.

I hope it helps you if you have the same problem!

**Long live ZCASH** ...
Good day to all!

**Comment by nuttycom** [comment]
This appears to have been a wallet issue that was incorrectly filed as a lightwalletd issue, but I'm glad that you found a solution.
