### ISSUE TITLE
Improve lightwalletd reorg detection

### ISSUE THREAD

**Issue by gmale** [zcash/lightwalletd#362]
Currently, lightwalletd detects reorgs by forgetting and refetching the most recent block. Instead, this change would be to use the latest hash to detect reorgs.

Criteria:
- [ ] latest block height is stable (rather than constantly going back by one)
- [ ] reorgs are detected within a reasonable amount of time (currently ~2 seconds)

Optional stretch goals:
- avoid polling entirely
  - ideally, without making any RPC changes to Zcashd
  - perhaps, leverage getBlockTemplate RPC to know exactly when there is a new block

**Comment by defuse** [comment]
We should document the "correct" algorithm for handling reorgs across our entire stack, maybe even give it a ZIP. The psuedocode in @LarryRuane's comment here looks to me like it's at least pretty close if not right on to the correct algorithm for handling all edge cases: https://github.com/zcash/lightwalletd/pull/348#issuecomment-882876624
