### ISSUE TITLE
GetMempoolTx removed breaks wallet client

### ISSUE THREAD

**Issue by hhanh00** [zcash/lightwalletd#364]
**What is the bug?**
GetMempoolTx was removed in favor of GetMempoolStream. 

The commit message says it has never been used.
But once an API is deployed to production, clients will assume it is available.

**Additional context**
Unfortunately, this break Y/ZWallet which uses this API. We could switch to the new API but IMO, `GetMempoolStream`
isn't always the best solution.

Pro:
GetMempoolStream is more reactive than GetMempoolTx 

Con:
- GetMempoolTx allows the device to go to sleep at a deterministic interval (the polling rate). With GetMempoolStream, the device will not sleep if there is a continuous stream of new transactions.
- After coming back from sleep, the app needs to start GetMempoolStream from the beginning or it may miss some transactions. GetMempoolTx has a filtering ability.

**Solution**
I'd like to keep GetMempoolTx side by side with GetMempoolStream.

Thanks,
--h

**Comment by daira** [comment]
Let's revert the removal of `GetMempoolTx`, at least for now.

**Comment by LarryRuane** [comment]
Sorry I removed this when you were still depending on it! It's been restored by #374, which is in the `master` branch, and the latest release [v0.4.9](https://github.com/zcash/lightwalletd/releases/tag/v0.4.9)
