### ISSUE TITLE
Upgrade Kubernetes API version

### ISSUE THREAD

**Issue by defuse** [zcash/lightwalletd#378]
> The Kubernetes API Server component in versions 1.1-1.14, and versions prior to 1.15.10, 1.16.7 and 1.17.3 allows an authorized user who sends malicious YAML payloads to cause the kube-apiserver to consume excessive CPU cycles while parsing YAML.

**Comment by LarryRuane** [comment]
GitHub shows me that same security alert, but I don't know how to fix this, any ideas?

**Comment by LarryRuane** [comment]
@defuse - can you verify that this is fixed? I no longer see the warning at the top of the main page of the lightwalletd repo, and would like to verify that you don't either. Thanks!
