### ISSUE TITLE
Add Orchard commitment to GetTreeState gRPC

### ISSUE THREAD

**Issue by LarryRuane** [zcash/lightwalletd#379]
Support for this was added to `zcashd`'s `z_gettreestate` RPC by https://github.com/zcash/zcash/pull/5560, this should be a simple change.

**Comment by steven-ecc** [comment]
@LarryRuane Currently GetTreeState returns only the Sapling finalState as the "tree" value. Should this now return saplingTree and orchardTree or how would you suggest the output is structured?
