### ISSUE TITLE
Reorg race condition that can cause rare crashes

### ISSUE THREAD

**Issue by defuse** [zcash/lightwalletd#408]
There's a race condition that can cause a lightwalletd crash when a reorg occurs at just the right time.

`getBlockFromRPC` first calls `getblock` to get the block into the `block` variable:

https://github.com/zcash/lightwalletd/blob/2d3943b8e995a3b2c5648ec9859dccc67c535386/common/common.go#L267-L268

Then, it makes another call to `getblock` and puts the block data into the `block1` variable:

https://github.com/zcash/lightwalletd/blob/2d3943b8e995a3b2c5648ec9859dccc67c535386/common/common.go#L285-L291

It then loops over `block`'s transactions, but indexes into `block1`. If `block` and `block1` are identical blocks, this should be fine. But if `block` has more transactions than `block1`, which could occur if there's a reorg at just the right time, it will index out of bounds into `block1` and crash.

https://github.com/zcash/lightwalletd/blob/2d3943b8e995a3b2c5648ec9859dccc67c535386/common/common.go#L295-L296

The data here is coming from zcashd, so this crash can not be triggered intentionally to DoS the server.

**Comment by defuse** [comment]
Suggested fix: Make the verbose call to getblock first (to get `block1), then fetch the block using `getblock <hash>` (to get `block`).

**Comment by LarryRuane** [comment]
Closed by #409
