### ISSUE TITLE
Add note commitment tree sizes to `CompactBlock` values.

### ISSUE THREAD

**Issue by nuttycom** [zcash/lightwalletd#432]
https://github.com/zcash/librustzcash/pull/831/commits/81640abd381098ff262dc80e5f3e38c13b0c8778 adds Sapling and Orchard note commitment tree sizes to the `CompactBlock` data structure. These should represent the total size of the respective note commitment trees as of the end of the block, such that for each pool the size of the commitment tree from the previous block plus the number of notes is equal to the size at the end of the current block.

**Comment by LarryRuane** [comment]
Kris, just to confirm my understanding:

The lightwalletd needs to compute these two values (counters) by initializing them to zero, then inspecting the transactions in each block starting with the genesis block (or, actually, it's sufficient to begin at Sapling activation), incrementing the counters according to the block's transactions' note commitments. Is that correct; there's no way to get these values directly from existing zcashd RPCs? Lightwalletd will need to scan each block?

Also, please excuse the basic question, but in the case of Sapling, are the note commitments associated with spends or outputs (or both)? I assume that for Orchard, the number of note commitments is just the number of actions in the transaction.

**Comment by nuttycom** [comment]
This shouldn't require lightwalletd to compute the sizes; after zcashd v5.6.0 this information will be exposed as part of the `getblock` results, see https://github.com/zcash/zcash/pull/6677/commits/8b1ebc0ea220216456d8008c237343aaa37f8621. Computing these values locally would also work, but might not be necessary if you take advantage of the change to the RPC api.

Note commitments are associated just with Sapling outputs, and are 1:1: with Orchard actions, correct.

**Comment by LarryRuane** [comment]
Just to verify, the patch you linked to, https://github.com/zcash/librustzcash/commit/81640abd381098ff262dc80e5f3e38c13b0c8778, encodes the sizes as `uint32`. Is that okay, or should it be `uint64`?

**Comment by LarryRuane** [comment]
The zcashd code returns a `uint64_t`: https://github.com/zcash/zcash/commit/8b1ebc0ea220216456d8008c237343aaa37f8621#diff-decae4be02fb8a47ab4557fe74a9cb853bdfa3ec0fa1b515c0a1e5de91f4ad0bR284

**Comment by nuttycom** [comment]
> The zcashd code returns a `uint64_t`: [zcash/zcash@8b1ebc0#diff-decae4be02fb8a47ab4557fe74a9cb853bdfa3ec0fa1b515c0a1e5de91f4ad0bR284](https://github.com/zcash/zcash/commit/8b1ebc0ea220216456d8008c237343aaa37f8621#diff-decae4be02fb8a47ab4557fe74a9cb853bdfa3ec0fa1b515c0a1e5de91f4ad0bR284)

Given that these are depth 32 trees, the size can never exceed 2^32 leaves. I thought that it was most appropriate to use u32 values for the wire encoding; it saves a few bytes. Maybe the savings are too small to be worth it.
