### ISSUE TITLE
lightwalletd does not parse zebrad.toml

### ISSUE THREAD

**Issue by hhanh00** [zcash/lightwalletd#462]
**What is the bug?**
```
[hanh@archlinux lightwalletd]$ lightwalletd --zcash-conf-path ~/.config/zebrad.toml --no-tls-very-insecure --log-file /dev/stdout
{"app":"lightwalletd","buildDate":"","buildUser":"","gitCommit":"","level":"info","msg":"Starting gRPC server version v0.0.0.0-dev on 127.0.0.1:9067","time":"2023-10-26T11:18:19+08:00"}
{"app":"lightwalletd","level":"warning","msg":"Starting insecure no-TLS (plaintext) server","time":"2023-10-26T11:18:19+08:00"}
Starting insecure server
{"app":"lightwalletd","error":"failed to read config file: key-value delimiter not found: \"dnsseed.z.cash:8233\",\n","level":"fatal","msg":"setting up RPC connection to zcashd","time":"2023-10-26T11:18:19+08:00"}
Lightwalletd died with a Fatal error. Check logfile for details.
```

zebrad.toml was generated by using zebra generate. It passes validation from https://www.toml-lint.com/

**Additional context**

Offending part of zebrad.toml
```
initial_mainnet_peers = [
    "dnsseed.z.cash:8233",
    "dnsseed.str4d.xyz:8233",
    "mainnet.seeder.zfnd.org:8233",
    "mainnet.is.yolo.money:8233",
]
```

**Comment by conradoplg** [comment]
lightwalletd doesn't support the zebra config file format. You will need to create a "fake" zcash.conf with the zcashd format with the information required. Some information here https://zebra.zfnd.org/user/lightwalletd.html#sync-lightwalletd

**Comment by hhanh00** [comment]
Ok, thanks for letting me know

**Comment by LarryRuane** [comment]
I wasn't aware of this, would it be helpful if lightwalletd did support the `zebrad.toml` file format? That seems reasonable; I could make that code change if it would be helpful. And probably not that difficult as a `toml` parser library probably already exists.

**Comment by arya2** [comment]
> I wasn't aware of this, would it be helpful if lightwalletd did support the `zebrad.toml` file format? That seems reasonable; I could make that code change if it would be helpful. And probably not that difficult as a `toml` parser library probably already exists.

I think this would be convenient if you could make that change.

**Comment by LarryRuane** [comment]
If any of you could test #485 that would be helpful; I'm not set up to run `zebrad`. The logic is pretty simple so it should work the first time.
