### ISSUE TITLE
Add a way to disable caching so lightwalletd always gets data from node RPCs

### ISSUE THREAD

**Issue by arya2** [zcash/lightwalletd#480]
**What is your feature request?**

It would be nice to have a way to disable the cache in lightwalletd with a config field or an environment variable so that there's no initial sync and the gRPC method are purely a proxy for the node's RPC methods.

**How would this feature help you?**

This could help reduce storage requirements when using lightwalletd with Zebra, including in Zebra's CI.

**Comment by LarryRuane** [comment]
Hi @arya2, is the PR to fix this (#483) acceptable? If you have a chance, can you review or test?
