### ISSUE TITLE
Errors hard-code `zcashd` regardless of the actual full node backend

### ISSUE THREAD

**Issue by str4d** [zcash/lightwalletd#488]
For example:
https://github.com/zcash/lightwalletd/blob/6e3816b5834583c492c37ce05b0faaf9fe12c87f/frontend/service.go#L288-L290

This can lead to misleading bug reports, e.g. https://github.com/Electric-Coin-Company/zashi-android/issues/1422

**Comment by LarryRuane** [comment]
Thanks, Daira, I wonder why this issue didn't close automatically when I merged the PR? I wrote "Closes #488" in the PR description, I thought that [should do it](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). In the future, I'll try to remember to check.

**Comment by LarryRuane** [comment]
Oh sorry, I thought I had merged #488 some time ago, I see that you just did that, never mind!
