### ISSUE TITLE
USD in lightwallet?

### ISSUE THREAD

**Issue by sourcesolver** [zcash/lightwalletd#500]
I am using zecwallet light, which appears to communicate with lightwalletd. The zecwallet is not showing the current USD for the balance in the wallet. Doing some digging, it appears it should get this from lightwalletd.

- Am I correct?

- Does lightwalletd need additional configuration to support that??

- Is there a CLI way to confirm that info is available in lightwalletd?

**Comment by sourcesolver** [comment]
I did some followup research on this. This post appears to suggest that lightwalletd does NOT offer current prices (though at one time it was to be?)

[https://github.com/zcash/lightwalletd/pull/354](https://github.com/zcash/lightwalletd/pull/354)

But this post for zecwallet-lite appears to suggest that it can only get CURRENT prices from lightwalletd:

[https://github.com/zcash/lightwalletd/pull/354](https://forum.zcashcommunity.com/t/accurate-zec-prices-with-zecwallet/39310)

So does this mean for the time being that zecwallet-lite cannot show the current USD price for your wallet's balance?
If there is a way to do this, please point to a link...

**Comment by defuse** [comment]
Some history: ZecWallet maintained their own fork of lightwalletd that had support for fetching the current price. That feature was never merged into here. I'm not sure if any public servers still run that fork. I don't think zecwallet-lite is maintained any longer, but the Zingo wallet is based on the same codebase and might be the most similar (Zingo's website appears to be down at the moment).

Instead, to maintain privacy, currency conversion was [implemented in Zashi by fetching exchange rates from exchanges over Tor](https://electriccoin.co/blog/released-currency-conversion-transparent-history-and-tex-addresses-in-zashi/), which is a more private way to do it.

If you need price conversion I recommend using a different wallet (Zashi, Ywallet, Zingo).

**Comment by LarryRuane** [comment]
I think there's agreement to close this at least for the time being. Please reopen if needed.
